// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq7IFpHXOcs_iXXQbCqge4djlWEqsduCw',
    appId: '1:645344132828:web:52a1543c5d9efcf22abe19',
    messagingSenderId: '645344132828',
    projectId: 'flutter-proj-1-b3d72',
    authDomain: 'flutter-proj-1-b3d72.firebaseapp.com',
    storageBucket: 'flutter-proj-1-b3d72.appspot.com',
    measurementId: 'G-JTE2ZK5YBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ4rG0QYPhiWU8Q2OW7P9W0rB9RCMyC-c',
    appId: '1:645344132828:android:393ff06cdd42c5582abe19',
    messagingSenderId: '645344132828',
    projectId: 'flutter-proj-1-b3d72',
    storageBucket: 'flutter-proj-1-b3d72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh7tXkawBDcdDyFB5HqxN7q7uqfF6SJtM',
    appId: '1:645344132828:ios:c1c1fa86fdf2d8b02abe19',
    messagingSenderId: '645344132828',
    projectId: 'flutter-proj-1-b3d72',
    storageBucket: 'flutter-proj-1-b3d72.appspot.com',
    iosClientId:
        '645344132828-643hteia8sm0ue4mki3b9tak08ncqnb1.apps.googleusercontent.com',
    iosBundleId: 'com.example.proj1',
  );
}
